import React from 'react';
import { Link } from 'react-router-dom';
import { Globe, Webhook, Shield, CheckCircle, AlertTriangle, ArrowRight, Zap, Lock } from 'lucide-react';
import { CodeBlock } from '../components/code/CodeBlock';

export const GatewayWebhook: React.FC = () => {
  const webhookRequestParams = [
    { name: 'transactionReference', type: 'string', required: true, description: 'Unique reference for the transaction generated by AkuPay.' },
    { name: 'merchantRef', type: 'string', required: true, description: 'Merchant\'s unique transaction reference.' },
    { name: 'grossAmount', type: 'decimal', required: true, description: 'Total transaction amount including fees.' },
    { name: 'requestedAmount', type: 'decimal', required: true, description: 'Original amount requested by the merchant.' },
    { name: 'transactionFee', type: 'decimal', required: true, description: 'Fee charged by AkuPay for processing the transaction.' },
    { name: 'settlementAmount', type: 'decimal', required: true, description: 'Amount to be settled to the merchant after fees.' },
    { name: 'customerId', type: 'string', required: true, description: 'Unique customer identifier.' },
    { name: 'transactionDate', type: 'string', required: true, description: 'Date and time the transaction was completed (ISO 8601).' },
    { name: 'currencyCode', type: 'string', required: true, description: 'Currency of the transaction (e.g., NGN, USD).' },
    { name: 'callbackUrl', type: 'string', required: false, description: 'Merchant\'s callback URL where AkuPay sends transaction updates.' },
    { name: 'status', type: 'integer', required: true, description: 'Transaction status code (see Status Codes section).' },
    { name: 'paymentRequestor', type: 'string', required: true, description: 'Source of payment request (e.g., WEB, MOBILE).' },
    { name: 'errorCode', type: 'string', required: false, description: 'Error code if the transaction failed.' },
    { name: 'errorMessage', type: 'string', required: false, description: 'Descriptive error message if any issue occurred.' },
    { name: 'externalRef', type: 'string', required: false, description: 'Reference used by external processors (if applicable).' },
    { name: 'paymentSource', type: 'string', required: true, description: 'Payment source used (e.g., CARD, BANK, OPay).' },
    { name: 'metadata', type: 'object', required: false, description: 'Custom data provided by the merchant (e.g., promo code, device type).' },
    { name: 'createdDate', type: 'string', required: true, description: 'Timestamp when the transaction record was created.' },
    { name: 'refundedAmount', type: 'decimal', required: false, description: 'Total amount refunded for the transaction.' },
    { name: 'lastRefundDate', type: 'string', required: false, description: 'Timestamp of the most recent refund event.' }
  ];

  const bestPractices = [
    'Use HTTPS endpoints for webhook URLs',
    'Implement idempotency to handle duplicate events',
    'Verify webhook signatures for security',
    'Return HTTP 200 status for successful processing',
    'Implement proper error handling and logging',
    'Store webhook events for audit and reconciliation',
    'Handle webhook retries gracefully',
    'Process webhooks asynchronously to avoid timeouts',
  ];

  const webhookRequestBodyJson = `{
  "transactionReference": "TXN-20250929-123456",
  "merchantRef": "MER-99887766",
  "grossAmount": 1500.00,
  "requestedAmount": 1500.00,
  "transactionFee": 25.50,
  "settlementAmount": 1474.50,
  "customerId": "CUS-55667788",
  "transactionDate": "2025-09-29T14:25:30",
  "currencyCode": "NGN",
  "callbackUrl": "https://merchant.example.com/callback",
  "status": 1,
  "paymentRequestor": "WEB",
  "errorCode": null,
  "errorMessage": null,
  "externalRef": "EXT-REF-12345",
  "paymentSource": "CARD",
  "metadata": {
    "deviceType": "MOBILE",
    "customerEmail": "customer@example.com",
    "promoCode": "WELCOME100"
  },
  "createdDate": "2025-09-29T14:20:00",
  "refundedAmount": 200.00,
  "lastRefundDate": "2025-09-29T15:00:00"
}`;

  const webhookResponseJson = `{
  "authentication": {
    "threeDS": {"status": "Y", "eci": "05"},
    "threeDS2": {"status": "N", "challengeIndicator": "04"},
    "amount": 100.50,
    "time": "2025-03-17T12:34:56Z",
    "transactionId": "txn_123456789",
    "version": "2.1.0"
  },
  "authorizationResponse": {
    "cardSecurityCodeError": "N",
    "commercialCardIndicator": "Y",
    "date": "2025-03-17",
    "financialNetworkCode": "VISA",
    "financialNetworkDate": "2025-03-17",
    "posData": "123456",
    "posEntryMode": "05",
    "processingCode": "00",
    "responseCode": "00",
    "stan": "123456",
    "time": "12:34:56",
    "transactionIdentifier": "456789123"
  },
  "device": {"browser": "Chrome"},
  "gatewayEntryPoint": "WEB",
  "merchant": "Merchant_001",
  "order": {
    "amount": 100.50,
    "authenticationStatus": "SUCCESS",
    "chargeback": {"amount": 0.00, "currency": "USD"},
    "creationTime": "2025-03-17T12:00:00Z",
    "currency": "USD",
    "id": "order_987654321",
    "lastUpdatedTime": "2025-03-17T12:45:00Z",
    "merchantAmount": 98.00,
    "merchantCategoryCode": "5411",
    "merchantCurrency": "USD",
    "notificationUrl": "https://merchant.com/webhook",
    "reference": "INV-20250317-001",
    "status": "COMPLETED",
    "totalAuthorizedAmount": 100.50,
    "totalCapturedAmount": 100.50,
    "totalDisbursedAmount": 98.00,
    "totalRefundedAmount": 0.00
  },
  "response": {
    "acquirerCode": "00",
    "acquirerMessage": "Approved",
    "cardSecurityCode": {"acquirerCode": "00", "gatewayCode": "APPROVED"},
    "gatewayCode": "APPROVED",
    "gatewayRecommendation": "PROCEED"
  },
  "result": "SUCCESS",
  "sourceOfFunds": {
    "provided": {
      "card": {
        "brand": "VISA",
        "expiry": {"month": "12", "year": "2027"},
        "fundingMethod": "CREDIT",
        "number": "411111******1111",
        "scheme": "VISA",
        "storedOnFile": "YES"
      }
    },
    "type": "CARD"
  },
  "timeOfLastUpdate": "2025-03-17T12:45:00Z",
  "timeOfRecord": "2025-03-17T12:34:56Z",
  "transaction": {
    "acquirer": {
      "batch": 12345,
      "date": "2025-03-17",
      "id": "acq_987654",
      "merchantId": "mid_456789",
      "settlementDate": "2025-03-18",
      "timeZone": "UTC",
      "transactionId": "txn_123456789"
    },
    "amount": 100.50,
    "authenticationStatus": "SUCCESS",
    "authorizationCode": "AUTH123",
    "currency": "USD",
    "id": "txn_123456789",
    "receipt": "RCPT-123456",
    "reference": "INV-20250317-001",
    "source": "WEB",
    "stan": "123456",
    "terminal": "TID12345",
    "type": "PURCHASE"
  },
  "version": "1.0"
}`;

  return (
    <div className="max-w-5xl mx-auto">
      {/* Header */}
      <div className="mb-12">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-xl bg-accent-500/10 border border-accent-500/20">
            <Webhook className="h-6 w-6 text-accent-400" />
          </div>
          <h1 className="text-3xl font-bold text-white">Webhook</h1>
        </div>
        <p className="text-lg text-white/60 leading-relaxed max-w-3xl">
          Kiwi Finance sends webhook notifications to you whenever there is a change in transaction status.
          Webhooks help ensure your system stays synchronized without constant polling.
        </p>
      </div>

      {/* Feature Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
        {/* Real-time Updates Card */}
        <div className="group relative overflow-hidden rounded-2xl bg-gradient-to-br from-accent-500/10 via-accent-500/5 to-transparent border border-accent-500/20 p-6 hover:border-accent-500/40 transition-all duration-300">
          <div className="absolute -top-24 -right-24 w-48 h-48 bg-accent-500/20 rounded-full blur-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

          <div className="relative">
            <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-accent-500/20 mb-4">
              <Zap className="h-6 w-6 text-accent-400" />
            </div>

            <h3 className="text-xl font-semibold text-white mb-2">Real-time Updates</h3>
            <p className="text-sm text-white/50 mb-5 leading-relaxed">
              Get instant notifications for all payment events as they happen.
            </p>

            <ul className="space-y-3">
              {[
                'Instant payment notifications',
                'Automatic status synchronization',
                'Reliable event delivery',
                'Retry mechanisms',
              ].map((feature, index) => (
                <li key={index} className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-5 h-5 rounded-full bg-accent-500/20">
                    <CheckCircle className="h-3 w-3 text-accent-400" />
                  </div>
                  <span className="text-sm text-white/70">{feature}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Security Card */}
        <div className="group relative overflow-hidden rounded-2xl bg-gradient-to-br from-kiwi-500/10 via-kiwi-500/5 to-transparent border border-kiwi-500/20 p-6 hover:border-kiwi-500/40 transition-all duration-300">
          <div className="absolute -top-24 -right-24 w-48 h-48 bg-kiwi-500/20 rounded-full blur-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

          <div className="relative">
            <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-kiwi-500/20 mb-4">
              <Shield className="h-6 w-6 text-kiwi-400" />
            </div>

            <h3 className="text-xl font-semibold text-white mb-2">Security</h3>
            <p className="text-sm text-white/50 mb-5 leading-relaxed">
              Enterprise-grade security for all webhook communications.
            </p>

            <ul className="space-y-3">
              {[
                'HTTPS-only delivery',
                'Signature verification',
                'IP whitelisting support',
                'Encrypted payloads',
              ].map((feature, index) => (
                <li key={index} className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-5 h-5 rounded-full bg-kiwi-500/20">
                    <Lock className="h-3 w-3 text-kiwi-400" />
                  </div>
                  <span className="text-sm text-white/70">{feature}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Webhook Request Body */}
      <div className="mb-12">
        <h2 className="text-xl font-semibold text-white mb-6">Webhook Request Body</h2>
        <CodeBlock code={webhookRequestBodyJson} language="json" />

        <div className="group relative overflow-hidden rounded-2xl bg-gradient-to-br from-yellow-500/10 via-yellow-500/5 to-transparent border border-yellow-500/20 p-6 mt-6">
          <div className="absolute -top-24 -right-24 w-48 h-48 bg-yellow-500/20 rounded-full blur-3xl opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

          <div className="relative flex items-start gap-4">
            <div className="p-2 rounded-xl bg-yellow-500/20 flex-shrink-0">
              <AlertTriangle className="h-5 w-5 text-yellow-400" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-white mb-2">Note</h3>
              <p className="text-sm text-white/70">
                Fields such as <strong className="text-yellow-400">errorCode</strong>, <strong className="text-yellow-400">errorMessage</strong>, <strong className="text-yellow-400">externalRef</strong>,{' '}
                <strong className="text-yellow-400">metadata</strong>, and <strong className="text-yellow-400">refundedAmount</strong> are optional.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Webhook Request Parameters */}
      <div className="mb-12">
        <h2 className="text-xl font-semibold text-white mb-4">Webhook Request Parameters</h2>
        <p className="text-white/60 mb-6">
          The following parameters are sent in the webhook request body:
        </p>

        <div className="glass rounded-2xl overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-white/5">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/50 uppercase tracking-wider">Parameter</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/50 uppercase tracking-wider">Type</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/50 uppercase tracking-wider">Required</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-white/50 uppercase tracking-wider">Description</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {webhookRequestParams.map((param, index) => (
                  <tr key={index} className="hover:bg-white/5 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-mono text-kiwi-400">{param.name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-mono text-white/60">{param.type}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${
                        param.required
                          ? 'bg-red-500/20 text-red-400 border-red-500/30'
                          : 'bg-white/10 text-white/60 border-white/20'
                      }`}>
                        {param.required ? 'Yes' : 'No'}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-sm text-white/60">{param.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Webhook Response Example */}
      <div className="mb-12">
        <h2 className="text-xl font-semibold text-white mb-4">Webhook Response Example</h2>
        <p className="text-white/60 mb-6">
          This response object provides detailed information about the transaction, authentication, authorization, and settlement data.
        </p>
        <CodeBlock code={webhookResponseJson} language="json" />
      </div>

      {/* Best Practices */}
      <div className="mb-12">
        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-2 rounded-xl bg-kiwi-500/20">
              <CheckCircle className="h-5 w-5 text-kiwi-400" />
            </div>
            <h3 className="text-lg font-semibold text-white">Implementation Guidelines</h3>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {bestPractices.map((practice, index) => (
              <div key={index} className="flex items-start gap-3 p-3 rounded-xl hover:bg-white/5 transition-colors">
                <div className="flex items-center justify-center w-5 h-5 rounded-full bg-kiwi-500/20 flex-shrink-0 mt-0.5">
                  <CheckCircle className="h-3 w-3 text-kiwi-400" />
                </div>
                <span className="text-sm text-white/70">{practice}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* CTA */}
      <div className="relative overflow-hidden rounded-2xl">
        <div className="absolute inset-0 bg-gradient-to-r from-kiwi-500 to-accent-500 opacity-90" />
        <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZGVmcz48cGF0dGVybiBpZD0iZ3JpZCIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBwYXR0ZXJuVW5pdHM9InVzZXJTcGFjZU9uVXNlIj48cGF0aCBkPSJNIDQwIDAgTCAwIDAgMCA0MCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJ3aGl0ZSIgc3Ryb2tlLW9wYWNpdHk9IjAuMSIgc3Ryb2tlLXdpZHRoPSIxIi8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSJ1cmwoI2dyaWQpIi8+PC9zdmc+')] opacity-30" />

        <div className="relative p-8 text-center">
          <div className="flex items-center justify-center gap-2 mb-3">
            <Globe className="h-6 w-6 text-white" />
            <h2 className="text-xl font-bold text-white">What's Next</h2>
          </div>
          <p className="text-white/80 mb-6">
            Return to Gateway Checkout overview or explore other API sections
          </p>
          <Link
            to="/gateway-checkout"
            className="inline-flex items-center gap-2 px-6 py-3 bg-white text-dark font-semibold rounded-xl hover:bg-white/90 transition-colors"
          >
            Back to Gateway Checkout
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    </div>
  );
};
