import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';
import { PageHeader } from '../components/docs/PageHeader';
import { PropertyTable } from '../components/docs/PropertyTable';
import { Callout } from '../components/docs/Callout';
import { CodeBlock } from '../components/code/CodeBlock';

export const GatewayWebhook: React.FC = () => {
  const webhookRequestParams = [
    { name: 'transactionReference', type: 'string', required: true, description: 'Unique reference for the transaction generated by Westrapay.' },
    { name: 'merchantRef', type: 'string', required: true, description: "Merchant's unique transaction reference." },
    { name: 'grossAmount', type: 'decimal', required: true, description: 'Total transaction amount including fees.' },
    { name: 'requestedAmount', type: 'decimal', required: true, description: 'Original amount requested by the merchant.' },
    { name: 'transactionFee', type: 'decimal', required: true, description: 'Fee charged by Westrapay for processing the transaction.' },
    { name: 'settlementAmount', type: 'decimal', required: true, description: 'Amount to be settled to the merchant after fees.' },
    { name: 'customerId', type: 'string', required: true, description: 'Unique customer identifier.' },
    { name: 'transactionDate', type: 'string', required: true, description: 'Date and time the transaction was completed (ISO 8601).' },
    { name: 'currencyCode', type: 'string', required: true, description: 'Currency of the transaction (e.g., USD, NGN).' },
    { name: 'callbackUrl', type: 'string', required: false, description: "Merchant's callback URL where Westrapay sends transaction updates." },
    { name: 'status', type: 'integer', required: true, description: 'Transaction status code (see Status Codes section).' },
    { name: 'paymentRequestor', type: 'string', required: true, description: 'Source of payment request (e.g., WEB, MOBILE).' },
    { name: 'errorCode', type: 'string', required: false, description: 'Error code if the transaction failed.' },
    { name: 'errorMessage', type: 'string', required: false, description: 'Descriptive error message if any issue occurred.' },
    { name: 'externalRef', type: 'string', required: false, description: 'Reference used by external processors (if applicable).' },
    { name: 'paymentSource', type: 'string', required: true, description: 'Payment source used (e.g., CARD, BANK, OPay).' },
    { name: 'metadata', type: 'object', required: false, description: 'Custom data provided by the merchant (e.g., promo code, device type).' },
    { name: 'createdDate', type: 'string', required: true, description: 'Timestamp when the transaction record was created.' },
    { name: 'refundedAmount', type: 'decimal', required: false, description: 'Total amount refunded for the transaction.' },
    { name: 'lastRefundDate', type: 'string', required: false, description: 'Timestamp of the most recent refund event.' },
  ];

  const bestPractices = [
    'Use HTTPS endpoints for webhook URLs',
    'Implement idempotency to handle duplicate events',
    'Verify webhook signatures for security',
    'Return HTTP 200 status for successful processing',
    'Implement proper error handling and logging',
    'Store webhook events for audit and reconciliation',
    'Handle webhook retries gracefully',
    'Process webhooks asynchronously to avoid timeouts',
  ];

  const webhookRequestBodyJson = `{
  "transactionReference": "TXN-20250929-123456",
  "merchantRef": "MER-99887766",
  "grossAmount": 1500.00,
  "requestedAmount": 1500.00,
  "transactionFee": 25.50,
  "settlementAmount": 1474.50,
  "customerId": "CUS-55667788",
  "transactionDate": "2025-09-29T14:25:30",
  "currencyCode": "USD",
  "callbackUrl": "https://merchant.example.com/callback",
  "status": 1,
  "paymentRequestor": "WEB",
  "errorCode": null,
  "errorMessage": null,
  "externalRef": "EXT-REF-12345",
  "paymentSource": "CARD",
  "metadata": {
    "deviceType": "MOBILE",
    "customerEmail": "customer@example.com",
    "promoCode": "WELCOME100"
  },
  "createdDate": "2025-09-29T14:20:00",
  "refundedAmount": 200.00,
  "lastRefundDate": "2025-09-29T15:00:00"
}`;

  const webhookResponseJson = `{
  "authentication": {
    "threeDS": {"status": "Y", "eci": "05"},
    "threeDS2": {"status": "N", "challengeIndicator": "04"},
    "amount": 100.50,
    "time": "2025-03-17T12:34:56Z",
    "transactionId": "txn_123456789",
    "version": "2.1.0"
  },
  "authorizationResponse": {
    "cardSecurityCodeError": "N",
    "commercialCardIndicator": "Y",
    "date": "2025-03-17",
    "financialNetworkCode": "VISA",
    "financialNetworkDate": "2025-03-17",
    "posData": "123456",
    "posEntryMode": "05",
    "processingCode": "00",
    "responseCode": "00",
    "stan": "123456",
    "time": "12:34:56",
    "transactionIdentifier": "456789123"
  },
  "device": {"browser": "Chrome"},
  "gatewayEntryPoint": "WEB",
  "merchant": "Merchant_001",
  "order": {
    "amount": 100.50,
    "authenticationStatus": "SUCCESS",
    "chargeback": {"amount": 0.00, "currency": "USD"},
    "creationTime": "2025-03-17T12:00:00Z",
    "currency": "USD",
    "id": "order_987654321",
    "lastUpdatedTime": "2025-03-17T12:45:00Z",
    "merchantAmount": 98.00,
    "merchantCategoryCode": "5411",
    "merchantCurrency": "USD",
    "notificationUrl": "https://merchant.com/webhook",
    "reference": "INV-20250317-001",
    "status": "COMPLETED",
    "totalAuthorizedAmount": 100.50,
    "totalCapturedAmount": 100.50,
    "totalDisbursedAmount": 98.00,
    "totalRefundedAmount": 0.00
  },
  "response": {
    "acquirerCode": "00",
    "acquirerMessage": "Approved",
    "cardSecurityCode": {"acquirerCode": "00", "gatewayCode": "APPROVED"},
    "gatewayCode": "APPROVED",
    "gatewayRecommendation": "PROCEED"
  },
  "result": "SUCCESS",
  "sourceOfFunds": {
    "provided": {
      "card": {
        "brand": "VISA",
        "expiry": {"month": "12", "year": "2027"},
        "fundingMethod": "CREDIT",
        "number": "411111******1111",
        "scheme": "VISA",
        "storedOnFile": "YES"
      }
    },
    "type": "CARD"
  },
  "timeOfLastUpdate": "2025-03-17T12:45:00Z",
  "timeOfRecord": "2025-03-17T12:34:56Z",
  "transaction": {
    "acquirer": {
      "batch": 12345,
      "date": "2025-03-17",
      "id": "acq_987654",
      "merchantId": "mid_456789",
      "settlementDate": "2025-03-18",
      "timeZone": "UTC",
      "transactionId": "txn_123456789"
    },
    "amount": 100.50,
    "authenticationStatus": "SUCCESS",
    "authorizationCode": "AUTH123",
    "currency": "USD",
    "id": "txn_123456789",
    "receipt": "RCPT-123456",
    "reference": "INV-20250317-001",
    "source": "WEB",
    "stan": "123456",
    "terminal": "TID12345",
    "type": "PURCHASE"
  },
  "version": "1.0"
}`;

  return (
    <div className="max-w-4xl">
      <PageHeader
        label="Gateway Integration"
        title="Gateway Webhook"
        description="Westrapay sends real-time webhook notifications to your configured endpoint on every transaction status change. Keep your system synchronized without polling."
      />

      {/* Webhook Payload */}
      <h2 className="text-base font-semibold text-slate-900 mb-4">Webhook Payload</h2>
      <CodeBlock code={webhookRequestBodyJson} language="json" />

      <Callout type="note">
        Fields marked optional (errorCode, errorMessage, externalRef, metadata, refundedAmount, lastRefundDate) may be absent or null.
      </Callout>

      {/* Payload Parameters */}
      <h2 className="text-base font-semibold text-slate-900 mb-4 mt-8">Payload Parameters</h2>
      <PropertyTable properties={webhookRequestParams} />

      {/* Response Example */}
      <h2 className="text-base font-semibold text-slate-900 mb-4 mt-8">Response Example</h2>
      <p className="text-[13px] text-slate-500 mb-4">
        This response object provides detailed information about the transaction, authentication, authorization, and settlement data.
      </p>
      <CodeBlock code={webhookResponseJson} language="json" />

      {/* Best Practices */}
      <h2 className="text-base font-semibold text-slate-900 mb-4 mt-8">Best Practices</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
        {bestPractices.map((p, i) => (
          <div
            key={i}
            className="flex items-start gap-2 px-3 py-2.5 bg-slate-50 border border-slate-100 rounded text-[13px] text-slate-600"
          >
            <span className="text-kiwi-500 flex-shrink-0 mt-0.5">✓</span>
            {p}
          </div>
        ))}
      </div>

      {/* Next step footer */}
      <div className="flex items-center justify-between pt-6 border-t border-slate-200 mt-10">
        <span className="text-[13px] text-slate-500">Next</span>
        <Link
          to="/gateway-integration"
          className="inline-flex items-center gap-2 px-4 py-2 text-[13px] font-medium text-kiwi-700 bg-kiwi-50 border border-kiwi-200 rounded hover:bg-kiwi-100 transition-colors"
        >
          Back to Gateway Integration <ArrowRight className="h-3.5 w-3.5" />
        </Link>
      </div>
    </div>
  );
};
